# Generated by Django 4.2.3 on 2023-08-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sex',
            field=models.CharField(default=str, max_length=5),
            preserve_default=False,
        ),
    ]
