# Generated by Django 4.2.3 on 2023-08-09 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
