# Generated by Django 4.2.3 on 2023-08-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='img-profile-default.png', upload_to='profile_images'),
        ),
    ]
