# Generated by Django 4.2.3 on 2023-08-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(choices=[('Kazakhstan', 'Kazakhstan'), ('Russia', 'Russia'), ('Germany', 'Germany'), ('USA', 'USA'), ('China', 'China')], max_length=50),
        ),
    ]
