# Generated by Django 4.2.3 on 2023-08-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_profile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sex',
            field=models.CharField(choices=[('man', 'man'), ('woman', 'woman')], max_length=5),
        ),
    ]
